title: Project

files:
  sortable: true

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  year:
    label: Year
    type:  text
    width: 1/4

  metadata:
    extends: metadata
  opengraph:
    extends: opengraph

  text:
    label: Text
    type:  textarea
